version: "3.1"

services:
  database:
    container_name: db
    restart: always
    image: "postgres:12"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-my-daily
    ports:
      - 5432:5432